import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import Image from "next/image";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <div className="h-screen bg-[#EBEBF6] grid grid-cols-6 relative overflow-hidden">
       
            
       <div className="col-span-1 px-11">
         <Sidebar />
       </div>
     {/* <Image
             className=" w-full absolute z-10 -top-96 -right-[500px] -rotate-6"
             src={"/Lines.png"}
             alt=""
             width={1500}
             height={100}
             ></Image> */}
       <div className="col-span-5 border-2 rounded-l-[60px] w-full h-screen bg-white overflow-scroll overflow-x-hidden">
         <div className="sticky top-0 z-30 bg-white">
           <Navbar />
         </div>
        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
